---
:supplier1: "/bins/2tlb8" 
:supplier2: "/bins/42lok" 
:supplier3: "/bins/15ktg"
# Added as a supplier that returns 500 - which is handled.
:supplier4: "/bins/doesnotexistwdqefwrgethrfweqdefwrbrwfr" 



